 export const languages = [
    'English',
    'हिंदी',
    '中文',
    'Español',
    'Français',
    'Deutsch',
    'العربية',
    'Português',
    'Русский',
    '日本語',
    'मराठी',
    'ગુજરાતી',
    'தமிழ்',
    'తెలుగు',
    'বাংলা',
  ];